### ISSUE TITLE
TypeError: accept is not a function

### ISSUE THREAD

**Issue by SteveCruise** [auth0/socketio-jwt#128]
```js
TypeError: accept is not a function
    at Object.success (/root/WebstormProjects/PHC/weex-server/node_modules/socketio-jwt/lib/index.js:117:9)
    at onJwtVerificationReady (/root/WebstormProjects/PHC/weex-server/node_modules/socketio-jwt/lib/index.js:179:19)
    at /root/WebstormProjects/PHC/weex-server/node_modules/jsonwebtoken/verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```

**Comment by LaurenceStokes** [comment]
@SteveCruise did you ever find a solution for this? :)

**Comment by nowrap** [comment]
I am facing the same problem. It occurs when using socketioJwt.authorize with handshake: true.

**Comment by 01speed1** [comment]
same problem here with handshake in true

**Comment by jbaudanza** [comment]
I had the same problem. As @nowrap, the solution is to use authorize() as middleware, not as an event handler.
